"""
PDF Payroll Summary Generation for Just Jon Handyman Services
Uses ReportLab to generate per-worker payroll summaries
"""
import os
from io import BytesIO
from datetime import date
from decimal import Decimal
from reportlab.lib.pagesizes import letter
from reportlab.lib.units import inch
from reportlab.lib import colors
from reportlab.platypus import SimpleDocTemplate, Table, TableStyle, Paragraph, Spacer
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.enums import TA_RIGHT, TA_CENTER

from ..schemas.payroll import PayrollWorkerSummary

# Company info
COMPANY_NAME = "Just Jon Industries INC."

# Theme (matches invoice_pdf.py)
THEME_COLOR = colors.HexColor("#1a1a2e")
ACCENT_COLOR = colors.HexColor("#2c5f78")
TEXT_COLOR = colors.HexColor("#333333")
LIGHT_BG = colors.HexColor("#f8f9fa")
BORDER_COLOR = colors.HexColor("#dee2e6")

LOGO_PATH = os.path.join(os.path.dirname(__file__), "justjon_logo.png")


def _fmt(val: Decimal) -> str:
    """Format a Decimal as currency string."""
    return f"${val:,.2f}"


def _draw_header_footer(canvas, doc):
    """Draw static header and footer on every page."""
    canvas.saveState()
    page_width, page_height = letter

    # --- HEADER ---
    header_height = 1.0 * inch
    canvas.setFillColor(THEME_COLOR)
    canvas.rect(0, page_height - header_height, page_width, header_height, fill=1, stroke=0)

    # Left side: Title
    canvas.setFillColor(colors.white)
    left_x = 0.5 * inch
    top_y = page_height - 0.35 * inch

    canvas.setFont("Helvetica-Bold", 22)
    canvas.drawString(left_x, top_y, "PAYROLL SUMMARY")

    canvas.setFont("Helvetica", 9)
    canvas.drawString(left_x, top_y - 22, COMPANY_NAME)

    # Right side: Logo or text fallback
    right_x = page_width - 0.5 * inch
    if os.path.exists(LOGO_PATH):
        try:
            canvas.drawImage(
                LOGO_PATH,
                right_x - 1.5 * inch,
                page_height - header_height + 0.15 * inch,
                width=1.5 * inch,
                height=0.7 * inch,
                preserveAspectRatio=True,
                anchor="sw",
                mask="auto",
            )
        except Exception:
            canvas.setFont("Helvetica-Bold", 12)
            canvas.drawRightString(right_x, top_y - 5, "Just Jon")
    else:
        canvas.setFont("Helvetica-Bold", 12)
        canvas.drawRightString(right_x, top_y - 5, "Just Jon")

    # --- FOOTER ---
    canvas.setStrokeColor(BORDER_COLOR)
    canvas.setLineWidth(0.5)
    canvas.line(0.5 * inch, 0.6 * inch, page_width - 0.5 * inch, 0.6 * inch)

    canvas.setFillColor(colors.HexColor("#999999"))
    canvas.setFont("Helvetica", 7)
    canvas.drawRightString(right_x, 0.3 * inch, "Generated by OBATEK Payroll System")

    canvas.restoreState()


def generate_payroll_pdf(
    summary: PayrollWorkerSummary,
    start_date: date,
    end_date: date,
) -> bytes:
    """Generate a payroll summary PDF for a single worker. Returns bytes."""
    buffer = BytesIO()

    doc = SimpleDocTemplate(
        buffer,
        pagesize=letter,
        topMargin=1.3 * inch,
        bottomMargin=0.9 * inch,
        leftMargin=0.5 * inch,
        rightMargin=0.5 * inch,
    )

    elements = []
    styles = getSampleStyleSheet()

    label_style = ParagraphStyle(
        "Label", parent=styles["Normal"],
        fontName="Helvetica-Bold", fontSize=9,
        textColor=TEXT_COLOR, leading=13,
    )
    value_style = ParagraphStyle(
        "Value", parent=styles["Normal"],
        fontName="Helvetica", fontSize=9,
        textColor=TEXT_COLOR, leading=13,
    )
    section_heading = ParagraphStyle(
        "SectionHeading", parent=styles["Normal"],
        fontName="Helvetica-Bold", fontSize=11,
        textColor=THEME_COLOR, spaceAfter=6, spaceBefore=12,
    )

    # ==============================
    # 1. WORKER INFO & PERIOD
    # ==============================
    period_str = f"{start_date.strftime('%B %d, %Y')} — {end_date.strftime('%B %d, %Y')}"

    info_data = [
        [Paragraph("Worker", label_style), Paragraph(summary.worker_name, value_style)],
        [Paragraph("Period", label_style), Paragraph(period_str, value_style)],
        [Paragraph("Entries", label_style), Paragraph(str(len(summary.entries)), value_style)],
    ]
    if summary.charges_hst:
        info_data.append([Paragraph("HST", label_style), Paragraph("Applicable (13%)", value_style)])

    t_info = Table(info_data, colWidths=[1.0 * inch, 4.0 * inch])
    t_info.setStyle(TableStyle([
        ("VALIGN", (0, 0), (-1, -1), "TOP"),
        ("LEFTPADDING", (0, 0), (-1, -1), 0),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 3),
    ]))
    elements.append(t_info)
    elements.append(Spacer(1, 0.25 * inch))

    # ==============================
    # 2. ENTRIES TABLE
    # ==============================
    elements.append(Paragraph("WORK ENTRIES", section_heading))

    # Determine the worker's hourly rate from first entry
    rate = summary.entries[0].labour_rate if summary.entries else Decimal("0")
    rate_str = f"${rate:,.2f}/hr"
    km_rate_str = f"${summary.entries[0].km_rate:,.2f}/km" if summary.entries else "$0.50/km"

    table_header = [
        "Date / Customer",
        "Hours",
        f"Labour @ {rate_str}",
        "KM",
        f"KM @ {km_rate_str}",
        "Materials",
    ]
    table_data = [table_header]

    for entry in summary.entries:
        date_str = entry.date.strftime("%b %d")
        cell_label = f"{date_str} – {entry.customer_name}"

        hours_str = f"{entry.billable_hours:,.2f}"
        if entry.billable_hours < entry.hours_worked:
            hours_str += "*"

        table_data.append([
            cell_label,
            hours_str,
            _fmt(entry.labour_cost),
            f"{entry.km_distance:,.1f}",
            _fmt(entry.km_cost),
            _fmt(entry.personal_materials) if entry.personal_materials > 0 else "—",
        ])

    # Totals row
    table_data.append([
        "TOTALS",
        f"{summary.total_hours:,.2f}",
        _fmt(summary.total_labour),
        f"{summary.total_km:,.1f}",
        _fmt(summary.total_km_cost),
        _fmt(summary.total_personal_materials) if summary.total_personal_materials > 0 else "—",
    ])

    col_widths = [2.1 * inch, 0.7 * inch, 1.2 * inch, 0.6 * inch, 1.1 * inch, 1.0 * inch]
    t_entries = Table(table_data, colWidths=col_widths, repeatRows=1)

    entry_style = [
        # Header row
        ("FONTNAME", (0, 0), (-1, 0), "Helvetica-Bold"),
        ("FONTSIZE", (0, 0), (-1, -1), 8),
        ("TEXTCOLOR", (0, 0), (-1, -1), TEXT_COLOR),
        ("BACKGROUND", (0, 0), (-1, 0), LIGHT_BG),
        ("LINEBELOW", (0, 0), (-1, 0), 1, BORDER_COLOR),
        # Totals row
        ("FONTNAME", (0, -1), (-1, -1), "Helvetica-Bold"),
        ("LINEABOVE", (0, -1), (-1, -1), 1.5, THEME_COLOR),
        ("BACKGROUND", (0, -1), (-1, -1), LIGHT_BG),
        # Alignment
        ("ALIGN", (1, 0), (-1, -1), "RIGHT"),
        ("ALIGN", (0, 0), (0, -1), "LEFT"),
        # Padding
        ("TOPPADDING", (0, 0), (-1, -1), 5),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 5),
        ("LEFTPADDING", (0, 0), (0, -1), 4),
    ]

    # Zebra striping
    for i in range(1, len(table_data) - 1):
        if i % 2 == 0:
            entry_style.append(("BACKGROUND", (0, i), (-1, i), LIGHT_BG))

    t_entries.setStyle(TableStyle(entry_style))
    elements.append(t_entries)

    # Minimum hours note
    has_minimum = any(e.billable_hours > e.hours_worked for e in summary.entries)
    if has_minimum:
        elements.append(Spacer(1, 4))
        note_style = ParagraphStyle(
            "Note", parent=styles["Normal"],
            fontName="Helvetica-Oblique", fontSize=7,
            textColor=colors.HexColor("#666666"),
        )
        elements.append(Paragraph("* 4-hour minimum applied", note_style))

    elements.append(Spacer(1, 0.3 * inch))

    # ==============================
    # 3. SUBTOTALS & HST
    # ==============================
    elements.append(Paragraph("PAYMENT SUMMARY", section_heading))

    totals_rows = [
        ["Labour Total", _fmt(summary.total_labour)],
        ["KM Reimbursement Total", _fmt(summary.total_km_cost)],
    ]
    if summary.total_personal_materials > 0:
        totals_rows.append(["Materials Reimbursement", _fmt(summary.total_personal_materials)])

    subtotal_before_hst = summary.total_labour + summary.total_km_cost + summary.total_personal_materials

    if summary.charges_hst:
        totals_rows.append(["", ""])  # Spacer row
        totals_rows.append(["Subtotal (before tax)", _fmt(subtotal_before_hst)])
        totals_rows.append(["HST on Labour (13%)", _fmt(summary.labour_hst)])
        totals_rows.append(["HST on KM (13%)", _fmt(summary.km_hst)])
        if summary.materials_hst > 0:
            totals_rows.append(["HST on Materials (13%)", _fmt(summary.materials_hst)])

    totals_rows.append(["TOTAL PAYROLL PAYOUT", _fmt(summary.grand_total)])

    t_totals = Table(totals_rows, colWidths=[3.0 * inch, 1.5 * inch])

    totals_style = [
        ("ALIGN", (0, 0), (-1, -1), "RIGHT"),
        ("FONTNAME", (0, 0), (-1, -1), "Helvetica"),
        ("FONTSIZE", (0, 0), (-1, -1), 10),
        ("TEXTCOLOR", (0, 0), (-1, -1), TEXT_COLOR),
        ("TOPPADDING", (0, 0), (-1, -1), 5),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 5),
        # Grand total row
        ("LINEABOVE", (0, -1), (-1, -1), 1.5, THEME_COLOR),
        ("FONTNAME", (0, -1), (-1, -1), "Helvetica-Bold"),
        ("FONTSIZE", (0, -1), (-1, -1), 12),
        ("TEXTCOLOR", (0, -1), (-1, -1), THEME_COLOR),
        ("TOPPADDING", (0, -1), (-1, -1), 10),
        ("BOTTOMPADDING", (0, -1), (-1, -1), 10),
    ]

    t_totals.setStyle(TableStyle(totals_style))

    # Right-align the totals table
    totals_wrapper = Table([[None, t_totals]], colWidths=[3.0 * inch, 4.5 * inch])
    elements.append(totals_wrapper)

    doc.build(elements, onFirstPage=_draw_header_footer, onLaterPages=_draw_header_footer)

    buffer.seek(0)
    return buffer.getvalue()
